### ISSUE TITLE
Event and Measurement tables need the "nw_" prefix

### ISSUE THREAD

**Issue by JRV77** [madgik/Docker-OptiquePostgres#1]
Hi,

To be compliant with the streams names from https://github.com/madgik/Docker-StreamServer named "nw_event" and "nw_measurement", the current SQL script for Northstream database need to be changed by adding a "nw_" prefix in front of the event and measurement tables.
Actually it should be something like "st_" for streams but leave it unless streams names are changed accordingly.
Thanks
Jean-Raphaël

**Comment by johnchronis** [comment]
Hi, 
I just removed the nw_ prefix from the datasets in the Docker-StreamServer repository. The table names now match across the containers.

Thanks,
Yannis

**Comment by JRV77** [comment]
That's also a good way to do it.

Thanks
Jean-Raphaël
